# Generated by Django 3.1.4 on 2020-12-26 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField(blank=True, max_length=600, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('customer_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('product_unit', models.CharField(max_length=50)),
                ('product_gst_percentage', models.FloatField()),
                ('product_rate_with_gst', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('invoice_json', models.TextField()),
                ('inventory_reflected', models.BooleanField(default=True)),
                ('books_reflected', models.BooleanField(default=True)),
                ('invoice_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoice.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
