# Generated by Django 3.1.4 on 2020-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_gst_percentage',
            new_name='gst_percentage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_hsn',
            new_name='hsn',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_unit',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_rate_with_gst',
            new_name='rate_without_gst',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service')], null=True),
        ),
    ]
