# Generated by Django 3.1.4 on 2020-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_auto_20201226_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gst_percentage',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rate_without_gst',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=200, null=True),
        ),
    ]
