# Generated by Django 3.1.4 on 2020-12-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_auto_20201226_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='books_reflected',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='inventory_reflected',
        ),
    ]
